Algoritmo "exercicio 2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Autor(a)    : Luany Boneli
// Data atual  : 26/05/2022
Var nome: caractere;
peso, altura, imc: REAL;

Inicio
escreva("Digite seu nome: ")
leia(nome)
escreva("Digite sua altura: ")
leia (altura)
escreva("Digite seu peso: ")
leia(peso)
imc <- peso/(altura*altura)
escreva("Nome: ", nome, "Altura", altura, " mts Peso", peso, "Kg")
escreva ("IMC: ", imc)


Fimalgoritmo