Algoritmo "exercicio 16"
// Disciplina   : [Linguagem e Lógica de Programação]
// Autor(a)    : Luany Boneli
// Data atual  : 04/06/2022

Var
   numero: INTEIRO;
   n: INTEIRO;

Inicio
   escreval("Entre com o número que deseja ver a tabuada")
   leia(numero)
   n <- 1;
   escreval("")
   enquanto n <= 10 faca
      escreval(numero,"x",n,"=", numero*n)
      n<-n+1;
   fimenquanto

Fimalgoritmo
© 2022 GitHub, Inc.